// Interface automatically generated by schemas-to-ts

import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';

export interface AboutUs {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    article?: any;
    seo?: Seo;
    locale: string;
    localizations?: { data: AboutUs[] };
  };
}
export interface AboutUs_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  article?: any;
  seo?: Seo_Plain;
  locale: string;
  localizations?: AboutUs[];
}

export interface AboutUs_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  article?: any;
  seo?: Seo_NoRelations;
  locale: string;
  localizations?: AboutUs[];
}

export interface AboutUs_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  article?: any;
  seo?: Seo_Plain;
  locale: string;
  localizations?: AboutUs[];
}
