// Interface automatically generated by schemas-to-ts

import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';

export interface Home {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    seo?: Seo;
    article?: any;
    locale: string;
    localizations?: { data: Home[] };
  };
}
export interface Home_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  seo?: Seo_Plain;
  article?: any;
  locale: string;
  localizations?: Home[];
}

export interface Home_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  seo?: Seo_NoRelations;
  article?: any;
  locale: string;
  localizations?: Home[];
}

export interface Home_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  seo?: Seo_Plain;
  article?: any;
  locale: string;
  localizations?: Home[];
}
