// Interface automatically generated by schemas-to-ts

import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';

export interface BlogMain {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    seo?: Seo;
    locale: string;
    localizations?: { data: BlogMain[] };
  };
}
export interface BlogMain_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  seo?: Seo_Plain;
  locale: string;
  localizations?: BlogMain[];
}

export interface BlogMain_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  seo?: Seo_NoRelations;
  locale: string;
  localizations?: BlogMain[];
}

export interface BlogMain_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  seo?: Seo_Plain;
  locale: string;
  localizations?: BlogMain[];
}
