name: test-create-json

on:
  push:
    branches: ["main"]
env:
  ECS_TASK_DEFINITION: task-defenetion.json

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: write

    steps:
      - name: get task defenetion json from secretes
        id: create-task-definition-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: ${{env.ECS_TASK_DEFINITION}}
          json: ${{ secrets.TASK_DEFINITION_JSON }}

      - name: check json output
        id: check-json
        env:
          output: ${{steps.create-task-definition-json.outputs}}
        run: echo "task-def output $output"
